/*
 *  MIT License
 *
 *  Copyright (c) 2020-2026 MASES s.r.l.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

/**************************************************************************************
 * <auto-generated>
 *      This code was generated from a template using JCOReflector v. 2.0.0.0
 * 
 *      Manual changes to this file may cause unexpected behavior in your application.
 *      Manual changes to this file will be overwritten if the code is regenerated.
 * </auto-generated>
 *************************************************************************************/

package system.data;

import org.mases.jcobridge.*;
import org.mases.jcobridge.netreflection.*;
import java.util.ArrayList;

// Import section
import system.data.DataRowVersion;
import system.data.DataColumn;
import system.data.DataRow;
import system.data.DataRelation;
import system.data.DataRowState;
import system.data.DataTable;


/**
 * The base .NET class managing System.Data.DataRow, System.Data.Common, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
 * <p>
 * 
 * .NET documentation at <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow" target="_top">https://learn.microsoft.com/dotnet/api/System.Data.DataRow</a>
 * <p>
 *
 * Powered by JCOBridge: more info at <a href="https://www.jcobridge.com" target="_top">https://www.jcobridge.com</a>
 *
 * @author  MASES s.r.l https://masesgroup.com
 * @version 2.0.0.0
 */
public class DataRow extends NetObject  {
    /**
     * Fully assembly qualified name: System.Data.Common, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
     */
    public static final String assemblyFullName = "System.Data.Common, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a";
    /**
     * Assembly name: System.Data.Common
     */
    public static final String assemblyShortName = "System.Data.Common";
    /**
     * Qualified class name: System.Data.DataRow
     */
    public static final String className = "System.Data.DataRow";
    static JCOBridge bridge = JCOBridgeInstance.getInstance(assemblyFullName);
    /**
     * The type managed from JCOBridge. See {@link JCType}
     */
    public static JCType classType = createType();
    static JCEnum enumInstance = null;
    JCObject classInstance = null;

    static JCType createType() {
        try {
            String classToCreate = className + ", "
                    + (JCOReflector.getUseFullAssemblyName() ? assemblyFullName : assemblyShortName);
            if (JCOReflector.getDebug())
                JCOReflector.writeLog("Creating %s", classToCreate);
            JCType typeCreated = bridge.GetType(classToCreate);
            if (JCOReflector.getDebug())
                JCOReflector.writeLog("Created: %s",
                        (typeCreated != null) ? typeCreated.toString() : "Returned null value");
            return typeCreated;
        } catch (JCException e) {
            JCOReflector.writeLog(e);
            return null;
        }
    }

    void addReference(String ref) throws Throwable {
        try {
            bridge.AddReference(ref);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }
    /**
     * Internal constructor. Use with caution
     *
     * @param instance the underlying bridge object: it must be a {@code JCObject}
     * @throws Throwable if {@code instance} is not a {@code JCObject}
     */
    public DataRow(java.lang.Object instance) throws Throwable {
        super(instance);
        if (instance instanceof JCObject) {
            classInstance = (JCObject) instance;
        } else
            throw new Exception("Cannot manage object, it is not a JCObject");
    }

    public String getJCOAssemblyName() {
        return assemblyFullName;
    }

    public String getJCOClassName() {
        return className;
    }

    public String getJCOObjectName() {
        return className + ", " + (JCOReflector.getUseFullAssemblyName() ? assemblyFullName : assemblyShortName);
    }

    public java.lang.Object getJCOInstance() {
        return classInstance;
    }

    public void setJCOInstance(JCObject instance) {
        classInstance = instance;
        super.setJCOInstance(classInstance);
    }

    public JCType getJCOType() {
        return classType;
    }
    /**
     * Try to cast the {@link IJCOBridgeReflected} instance into {@link DataRow}, a cast assert is made to check if types are compatible.
     * @param from {@link IJCOBridgeReflected} instance to be casted
     * @return {@link DataRow} instance
     * @throws java.lang.Throwable in case of error during cast operation
     */
    public static DataRow cast(IJCOBridgeReflected from) throws Throwable {
        NetType.AssertCast(classType, from);
        return new DataRow(from.getJCOInstance());
    }

    // Constructors section
    
    public DataRow() throws Throwable {
    }



    
    // Methods section
    
    /**
     * Invokes the .NET member HasVersion.
     *
     * @param version the argument of type {@code DataRowVersion}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.globalization.CultureNotFoundException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.HasVersion" target="_top">.NET documentation</a>
     */
    public boolean HasVersion(DataRowVersion version) throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.NotSupportedException, system.ArgumentOutOfRangeException, system.globalization.CultureNotFoundException, system.InvalidOperationException, system.ObjectDisposedException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectHasVersion = null;
        try {
            retObjectHasVersion = classInstance.Invoke("HasVersion", version == null ? null : version.getJCOInstance());
            return (boolean)retObjectHasVersion;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to convert %s into boolean", retObjectHasVersion != null ? retObjectHasVersion.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member IsNull.
     *
     * @param columnIndex the argument of type {@code int}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.ArrayTypeMismatchException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.RankException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.IsNull" target="_top">.NET documentation</a>
     */
    public boolean IsNull(int columnIndex) throws Throwable, system.ArgumentException, system.ArgumentNullException, system.PlatformNotSupportedException, system.ArgumentOutOfRangeException, system.InvalidOperationException, system.ArrayTypeMismatchException, system.NotSupportedException, system.ObjectDisposedException, system.RankException, system.IndexOutOfRangeException, system.FormatException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectIsNull = null;
        try {
            retObjectIsNull = classInstance.Invoke("IsNull", columnIndex);
            return (boolean)retObjectIsNull;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to convert %s into boolean", retObjectIsNull != null ? retObjectIsNull.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member IsNull.
     *
     * @param column the argument of type {@code DataColumn}
     * @param version the argument of type {@code DataRowVersion}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.globalization.CultureNotFoundException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.IsNull" target="_top">.NET documentation</a>
     */
    public boolean IsNull(DataColumn column, DataRowVersion version) throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ArgumentOutOfRangeException, system.globalization.CultureNotFoundException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectIsNull = null;
        try {
            retObjectIsNull = classInstance.Invoke("IsNull", column == null ? null : column.getJCOInstance(), version == null ? null : version.getJCOInstance());
            return (boolean)retObjectIsNull;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to convert %s into boolean", retObjectIsNull != null ? retObjectIsNull.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member IsNull.
     *
     * @param column the argument of type {@code DataColumn}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.globalization.CultureNotFoundException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.IsNull" target="_top">.NET documentation</a>
     */
    public boolean IsNull(DataColumn column) throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ArgumentOutOfRangeException, system.globalization.CultureNotFoundException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectIsNull = null;
        try {
            retObjectIsNull = classInstance.Invoke("IsNull", column == null ? null : column.getJCOInstance());
            return (boolean)retObjectIsNull;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to convert %s into boolean", retObjectIsNull != null ? retObjectIsNull.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member IsNull.
     *
     * @param columnName the argument of type {@code java.lang.String}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.IsNull" target="_top">.NET documentation</a>
     */
    public boolean IsNull(java.lang.String columnName) throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ObjectDisposedException, system.InvalidOperationException, system.IndexOutOfRangeException, system.ArgumentOutOfRangeException, system.FormatException, system.NotSupportedException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectIsNull = null;
        try {
            retObjectIsNull = classInstance.Invoke("IsNull", columnName);
            return (boolean)retObjectIsNull;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to convert %s into boolean", retObjectIsNull != null ? retObjectIsNull.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetColumnsInError.
     *
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetColumnsInError" target="_top">.NET documentation</a>
     */
    public DataColumn[] GetColumnsInError() throws Throwable {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetColumnsInError = null;
        try {
            ArrayList<DataColumn> resultingArrayList = new ArrayList<DataColumn>();
            retObjectGetColumnsInError = classInstance.Invoke("GetColumnsInError");
            JCObject resultingObjects = (JCObject)retObjectGetColumnsInError;
            for (java.lang.Object resultingObject : resultingObjects) {
			    resultingArrayList.add(new DataColumn(resultingObject));
            }
            DataColumn[] resultingArray = new DataColumn[resultingArrayList.size()];
            resultingArray = resultingArrayList.toArray(resultingArray);
            return resultingArray;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectGetColumnsInError != null ? retObjectGetColumnsInError.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetParentRow.
     *
     * @param relation the argument of type {@code DataRelation}
     * @param version the argument of type {@code DataRowVersion}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @throws system.ArgumentNullException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetParentRow" target="_top">.NET documentation</a>
     */
    public DataRow GetParentRow(DataRelation relation, DataRowVersion version) throws Throwable, system.ArgumentException, system.PlatformNotSupportedException, system.NotSupportedException, system.InvalidOperationException, system.IndexOutOfRangeException, system.ArgumentOutOfRangeException, system.FormatException, system.ObjectDisposedException, system.threading.LockRecursionException, system.threading.SynchronizationLockException, system.ArgumentNullException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetParentRow = null;
        try {
            retObjectGetParentRow = classInstance.Invoke("GetParentRow", relation == null ? null : relation.getJCOInstance(), version == null ? null : version.getJCOInstance());
            JCObject objGetParentRow = (JCObject)retObjectGetParentRow;
            return new DataRow(objGetParentRow);
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectGetParentRow != null ? retObjectGetParentRow.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetParentRow.
     *
     * @param relation the argument of type {@code DataRelation}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetParentRow" target="_top">.NET documentation</a>
     */
    public DataRow GetParentRow(DataRelation relation) throws Throwable, system.PlatformNotSupportedException, system.InvalidOperationException, system.IndexOutOfRangeException, system.ArgumentException, system.ArgumentOutOfRangeException, system.ArgumentNullException, system.FormatException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetParentRow = null;
        try {
            retObjectGetParentRow = classInstance.Invoke("GetParentRow", relation == null ? null : relation.getJCOInstance());
            JCObject objGetParentRow = (JCObject)retObjectGetParentRow;
            return new DataRow(objGetParentRow);
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectGetParentRow != null ? retObjectGetParentRow.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetParentRow.
     *
     * @param relationName the argument of type {@code java.lang.String}
     * @param version the argument of type {@code DataRowVersion}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetParentRow" target="_top">.NET documentation</a>
     */
    public DataRow GetParentRow(java.lang.String relationName, DataRowVersion version) throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ObjectDisposedException, system.InvalidOperationException, system.IndexOutOfRangeException, system.ArgumentOutOfRangeException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetParentRow = null;
        try {
            retObjectGetParentRow = classInstance.Invoke("GetParentRow", relationName, version == null ? null : version.getJCOInstance());
            JCObject objGetParentRow = (JCObject)retObjectGetParentRow;
            return new DataRow(objGetParentRow);
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectGetParentRow != null ? retObjectGetParentRow.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetParentRow.
     *
     * @param relationName the argument of type {@code java.lang.String}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetParentRow" target="_top">.NET documentation</a>
     */
    public DataRow GetParentRow(java.lang.String relationName) throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ObjectDisposedException, system.InvalidOperationException, system.IndexOutOfRangeException, system.ArgumentOutOfRangeException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetParentRow = null;
        try {
            retObjectGetParentRow = classInstance.Invoke("GetParentRow", relationName);
            JCObject objGetParentRow = (JCObject)retObjectGetParentRow;
            return new DataRow(objGetParentRow);
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectGetParentRow != null ? retObjectGetParentRow.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetChildRows.
     *
     * @param relation the argument of type {@code DataRelation}
     * @param version the argument of type {@code DataRowVersion}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetChildRows" target="_top">.NET documentation</a>
     */
    public DataRow[] GetChildRows(DataRelation relation, DataRowVersion version) throws Throwable, system.PlatformNotSupportedException, system.ArgumentNullException, system.IndexOutOfRangeException, system.ArgumentException, system.ArgumentOutOfRangeException, system.FormatException, system.InvalidOperationException, system.ObjectDisposedException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetChildRows = null;
        try {
            ArrayList<DataRow> resultingArrayList = new ArrayList<DataRow>();
            retObjectGetChildRows = classInstance.Invoke("GetChildRows", relation == null ? null : relation.getJCOInstance(), version == null ? null : version.getJCOInstance());
            JCObject resultingObjects = (JCObject)retObjectGetChildRows;
            for (java.lang.Object resultingObject : resultingObjects) {
			    resultingArrayList.add(new DataRow(resultingObject));
            }
            DataRow[] resultingArray = new DataRow[resultingArrayList.size()];
            resultingArray = resultingArrayList.toArray(resultingArray);
            return resultingArray;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectGetChildRows != null ? retObjectGetChildRows.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetChildRows.
     *
     * @param relation the argument of type {@code DataRelation}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetChildRows" target="_top">.NET documentation</a>
     */
    public DataRow[] GetChildRows(DataRelation relation) throws Throwable, system.PlatformNotSupportedException, system.ArgumentNullException, system.ArgumentOutOfRangeException, system.ArgumentException, system.InvalidOperationException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetChildRows = null;
        try {
            ArrayList<DataRow> resultingArrayList = new ArrayList<DataRow>();
            retObjectGetChildRows = classInstance.Invoke("GetChildRows", relation == null ? null : relation.getJCOInstance());
            JCObject resultingObjects = (JCObject)retObjectGetChildRows;
            for (java.lang.Object resultingObject : resultingObjects) {
			    resultingArrayList.add(new DataRow(resultingObject));
            }
            DataRow[] resultingArray = new DataRow[resultingArrayList.size()];
            resultingArray = resultingArrayList.toArray(resultingArray);
            return resultingArray;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectGetChildRows != null ? retObjectGetChildRows.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetChildRows.
     *
     * @param relationName the argument of type {@code java.lang.String}
     * @param version the argument of type {@code DataRowVersion}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetChildRows" target="_top">.NET documentation</a>
     */
    public DataRow[] GetChildRows(java.lang.String relationName, DataRowVersion version) throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ObjectDisposedException, system.InvalidOperationException, system.ArgumentOutOfRangeException, system.IndexOutOfRangeException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetChildRows = null;
        try {
            ArrayList<DataRow> resultingArrayList = new ArrayList<DataRow>();
            retObjectGetChildRows = classInstance.Invoke("GetChildRows", relationName, version == null ? null : version.getJCOInstance());
            JCObject resultingObjects = (JCObject)retObjectGetChildRows;
            for (java.lang.Object resultingObject : resultingObjects) {
			    resultingArrayList.add(new DataRow(resultingObject));
            }
            DataRow[] resultingArray = new DataRow[resultingArrayList.size()];
            resultingArray = resultingArrayList.toArray(resultingArray);
            return resultingArray;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectGetChildRows != null ? retObjectGetChildRows.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetChildRows.
     *
     * @param relationName the argument of type {@code java.lang.String}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetChildRows" target="_top">.NET documentation</a>
     */
    public DataRow[] GetChildRows(java.lang.String relationName) throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ObjectDisposedException, system.InvalidOperationException, system.ArgumentOutOfRangeException, system.IndexOutOfRangeException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetChildRows = null;
        try {
            ArrayList<DataRow> resultingArrayList = new ArrayList<DataRow>();
            retObjectGetChildRows = classInstance.Invoke("GetChildRows", relationName);
            JCObject resultingObjects = (JCObject)retObjectGetChildRows;
            for (java.lang.Object resultingObject : resultingObjects) {
			    resultingArrayList.add(new DataRow(resultingObject));
            }
            DataRow[] resultingArray = new DataRow[resultingArrayList.size()];
            resultingArray = resultingArrayList.toArray(resultingArray);
            return resultingArray;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectGetChildRows != null ? retObjectGetChildRows.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetParentRows.
     *
     * @param relation the argument of type {@code DataRelation}
     * @param version the argument of type {@code DataRowVersion}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetParentRows" target="_top">.NET documentation</a>
     */
    public DataRow[] GetParentRows(DataRelation relation, DataRowVersion version) throws Throwable, system.PlatformNotSupportedException, system.ArgumentNullException, system.IndexOutOfRangeException, system.ArgumentException, system.ArgumentOutOfRangeException, system.FormatException, system.InvalidOperationException, system.ObjectDisposedException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetParentRows = null;
        try {
            ArrayList<DataRow> resultingArrayList = new ArrayList<DataRow>();
            retObjectGetParentRows = classInstance.Invoke("GetParentRows", relation == null ? null : relation.getJCOInstance(), version == null ? null : version.getJCOInstance());
            JCObject resultingObjects = (JCObject)retObjectGetParentRows;
            for (java.lang.Object resultingObject : resultingObjects) {
			    resultingArrayList.add(new DataRow(resultingObject));
            }
            DataRow[] resultingArray = new DataRow[resultingArrayList.size()];
            resultingArray = resultingArrayList.toArray(resultingArray);
            return resultingArray;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectGetParentRows != null ? retObjectGetParentRows.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetParentRows.
     *
     * @param relation the argument of type {@code DataRelation}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetParentRows" target="_top">.NET documentation</a>
     */
    public DataRow[] GetParentRows(DataRelation relation) throws Throwable, system.PlatformNotSupportedException, system.ArgumentNullException, system.ArgumentOutOfRangeException, system.ArgumentException, system.InvalidOperationException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetParentRows = null;
        try {
            ArrayList<DataRow> resultingArrayList = new ArrayList<DataRow>();
            retObjectGetParentRows = classInstance.Invoke("GetParentRows", relation == null ? null : relation.getJCOInstance());
            JCObject resultingObjects = (JCObject)retObjectGetParentRows;
            for (java.lang.Object resultingObject : resultingObjects) {
			    resultingArrayList.add(new DataRow(resultingObject));
            }
            DataRow[] resultingArray = new DataRow[resultingArrayList.size()];
            resultingArray = resultingArrayList.toArray(resultingArray);
            return resultingArray;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectGetParentRows != null ? retObjectGetParentRows.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetParentRows.
     *
     * @param relationName the argument of type {@code java.lang.String}
     * @param version the argument of type {@code DataRowVersion}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetParentRows" target="_top">.NET documentation</a>
     */
    public DataRow[] GetParentRows(java.lang.String relationName, DataRowVersion version) throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ObjectDisposedException, system.InvalidOperationException, system.ArgumentOutOfRangeException, system.IndexOutOfRangeException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetParentRows = null;
        try {
            ArrayList<DataRow> resultingArrayList = new ArrayList<DataRow>();
            retObjectGetParentRows = classInstance.Invoke("GetParentRows", relationName, version == null ? null : version.getJCOInstance());
            JCObject resultingObjects = (JCObject)retObjectGetParentRows;
            for (java.lang.Object resultingObject : resultingObjects) {
			    resultingArrayList.add(new DataRow(resultingObject));
            }
            DataRow[] resultingArray = new DataRow[resultingArrayList.size()];
            resultingArray = resultingArrayList.toArray(resultingArray);
            return resultingArray;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectGetParentRows != null ? retObjectGetParentRows.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetParentRows.
     *
     * @param relationName the argument of type {@code java.lang.String}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetParentRows" target="_top">.NET documentation</a>
     */
    public DataRow[] GetParentRows(java.lang.String relationName) throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ObjectDisposedException, system.InvalidOperationException, system.ArgumentOutOfRangeException, system.IndexOutOfRangeException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetParentRows = null;
        try {
            ArrayList<DataRow> resultingArrayList = new ArrayList<DataRow>();
            retObjectGetParentRows = classInstance.Invoke("GetParentRows", relationName);
            JCObject resultingObjects = (JCObject)retObjectGetParentRows;
            for (java.lang.Object resultingObject : resultingObjects) {
			    resultingArrayList.add(new DataRow(resultingObject));
            }
            DataRow[] resultingArray = new DataRow[resultingArrayList.size()];
            resultingArray = resultingArrayList.toArray(resultingArray);
            return resultingArray;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectGetParentRows != null ? retObjectGetParentRows.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetColumnError.
     *
     * @param columnIndex the argument of type {@code int}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.ArrayTypeMismatchException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.RankException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetColumnError" target="_top">.NET documentation</a>
     */
    public java.lang.String GetColumnError(int columnIndex) throws Throwable, system.ArgumentException, system.ArgumentNullException, system.PlatformNotSupportedException, system.ArgumentOutOfRangeException, system.InvalidOperationException, system.ArrayTypeMismatchException, system.NotSupportedException, system.ObjectDisposedException, system.RankException, system.IndexOutOfRangeException, system.FormatException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetColumnError = null;
        try {
            retObjectGetColumnError = classInstance.Invoke("GetColumnError", columnIndex);
            return (java.lang.String)retObjectGetColumnError;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to convert %s into java.lang.String", retObjectGetColumnError != null ? retObjectGetColumnError.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetColumnError.
     *
     * @param column the argument of type {@code DataColumn}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.globalization.CultureNotFoundException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetColumnError" target="_top">.NET documentation</a>
     */
    public java.lang.String GetColumnError(DataColumn column) throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ArgumentOutOfRangeException, system.globalization.CultureNotFoundException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetColumnError = null;
        try {
            retObjectGetColumnError = classInstance.Invoke("GetColumnError", column == null ? null : column.getJCOInstance());
            return (java.lang.String)retObjectGetColumnError;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to convert %s into java.lang.String", retObjectGetColumnError != null ? retObjectGetColumnError.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member GetColumnError.
     *
     * @param columnName the argument of type {@code java.lang.String}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.GetColumnError" target="_top">.NET documentation</a>
     */
    public java.lang.String GetColumnError(java.lang.String columnName) throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ObjectDisposedException, system.InvalidOperationException, system.IndexOutOfRangeException, system.ArgumentOutOfRangeException, system.FormatException, system.NotSupportedException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectGetColumnError = null;
        try {
            retObjectGetColumnError = classInstance.Invoke("GetColumnError", columnName);
            return (java.lang.String)retObjectGetColumnError;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to convert %s into java.lang.String", retObjectGetColumnError != null ? retObjectGetColumnError.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member AcceptChanges.
     *
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.NotSupportedException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.diagnostics.tracing.EventSourceException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.AcceptChanges" target="_top">.NET documentation</a>
     */
    public void AcceptChanges() throws Throwable, system.NotSupportedException, system.ArgumentException, system.PlatformNotSupportedException, system.ArgumentOutOfRangeException, system.InvalidOperationException, system.FormatException, system.ArgumentNullException, system.diagnostics.tracing.EventSourceException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Invoke("AcceptChanges");
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member BeginEdit.
     *
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.globalization.CultureNotFoundException if the .NET member raises it
     * @throws system.RankException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.ArrayTypeMismatchException if the .NET member raises it
     * @throws system.InvalidCastException if the .NET member raises it
     * @throws system.OutOfMemoryException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.BeginEdit" target="_top">.NET documentation</a>
     */
    public void BeginEdit() throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ArgumentOutOfRangeException, system.globalization.CultureNotFoundException, system.RankException, system.IndexOutOfRangeException, system.ArrayTypeMismatchException, system.InvalidCastException, system.OutOfMemoryException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Invoke("BeginEdit");
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member CancelEdit.
     *
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.globalization.CultureNotFoundException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.RankException if the .NET member raises it
     * @throws system.ArrayTypeMismatchException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.CancelEdit" target="_top">.NET documentation</a>
     */
    public void CancelEdit() throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.NotSupportedException, system.ArgumentOutOfRangeException, system.globalization.CultureNotFoundException, system.InvalidOperationException, system.ObjectDisposedException, system.FormatException, system.IndexOutOfRangeException, system.RankException, system.ArrayTypeMismatchException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Invoke("CancelEdit");
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member ClearErrors.
     *
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.RankException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.ArrayTypeMismatchException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.ClearErrors" target="_top">.NET documentation</a>
     */
    public void ClearErrors() throws Throwable, system.ArgumentOutOfRangeException, system.PlatformNotSupportedException, system.threading.LockRecursionException, system.ArgumentNullException, system.InvalidOperationException, system.RankException, system.ArgumentException, system.ArrayTypeMismatchException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Invoke("ClearErrors");
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member Delete.
     *
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.globalization.CultureNotFoundException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.RankException if the .NET member raises it
     * @throws system.ArrayTypeMismatchException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.Delete" target="_top">.NET documentation</a>
     */
    public void Delete() throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.NotSupportedException, system.ArgumentOutOfRangeException, system.globalization.CultureNotFoundException, system.InvalidOperationException, system.ObjectDisposedException, system.IndexOutOfRangeException, system.RankException, system.ArrayTypeMismatchException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Invoke("Delete");
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member EndEdit.
     *
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.globalization.CultureNotFoundException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.RankException if the .NET member raises it
     * @throws system.ArrayTypeMismatchException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.EndEdit" target="_top">.NET documentation</a>
     */
    public void EndEdit() throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.NotSupportedException, system.ArgumentOutOfRangeException, system.globalization.CultureNotFoundException, system.InvalidOperationException, system.ObjectDisposedException, system.IndexOutOfRangeException, system.RankException, system.ArrayTypeMismatchException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Invoke("EndEdit");
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member RejectChanges.
     *
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.NotSupportedException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.diagnostics.tracing.EventSourceException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.RejectChanges" target="_top">.NET documentation</a>
     */
    public void RejectChanges() throws Throwable, system.NotSupportedException, system.ArgumentException, system.PlatformNotSupportedException, system.ArgumentOutOfRangeException, system.InvalidOperationException, system.FormatException, system.ArgumentNullException, system.diagnostics.tracing.EventSourceException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Invoke("RejectChanges");
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member SetAdded.
     *
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.RankException if the .NET member raises it
     * @throws system.ArrayTypeMismatchException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.SetAdded" target="_top">.NET documentation</a>
     */
    public void SetAdded() throws Throwable, system.ArgumentException, system.InvalidOperationException, system.PlatformNotSupportedException, system.IndexOutOfRangeException, system.ArgumentOutOfRangeException, system.FormatException, system.ArgumentNullException, system.RankException, system.ArrayTypeMismatchException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Invoke("SetAdded");
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member SetColumnError.
     *
     * @param columnIndex the argument of type {@code int}
     * @param error the argument of type {@code java.lang.String}
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.ArrayTypeMismatchException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.RankException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.SetColumnError" target="_top">.NET documentation</a>
     */
    public void SetColumnError(int columnIndex, java.lang.String error) throws Throwable, system.ArgumentException, system.ArgumentNullException, system.PlatformNotSupportedException, system.ArgumentOutOfRangeException, system.InvalidOperationException, system.ArrayTypeMismatchException, system.NotSupportedException, system.ObjectDisposedException, system.RankException, system.IndexOutOfRangeException, system.FormatException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Invoke("SetColumnError", columnIndex, error);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member SetColumnError.
     *
     * @param column the argument of type {@code DataColumn}
     * @param error the argument of type {@code java.lang.String}
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.globalization.CultureNotFoundException if the .NET member raises it
     * @throws system.ArrayTypeMismatchException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.RankException if the .NET member raises it
     * @throws system.InvalidCastException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.SetColumnError" target="_top">.NET documentation</a>
     */
    public void SetColumnError(DataColumn column, java.lang.String error) throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ArgumentOutOfRangeException, system.globalization.CultureNotFoundException, system.ArrayTypeMismatchException, system.InvalidOperationException, system.NotSupportedException, system.IndexOutOfRangeException, system.FormatException, system.RankException, system.InvalidCastException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Invoke("SetColumnError", column == null ? null : column.getJCOInstance(), error);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member SetColumnError.
     *
     * @param columnName the argument of type {@code java.lang.String}
     * @param error the argument of type {@code java.lang.String}
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @throws system.RankException if the .NET member raises it
     * @throws system.ArrayTypeMismatchException if the .NET member raises it
     * @throws system.InvalidCastException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.SetColumnError" target="_top">.NET documentation</a>
     */
    public void SetColumnError(java.lang.String columnName, java.lang.String error) throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ObjectDisposedException, system.InvalidOperationException, system.IndexOutOfRangeException, system.ArgumentOutOfRangeException, system.FormatException, system.NotSupportedException, system.RankException, system.ArrayTypeMismatchException, system.InvalidCastException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Invoke("SetColumnError", columnName, error);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member SetModified.
     *
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.RankException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @throws system.ArrayTypeMismatchException if the .NET member raises it
     * @throws system.InvalidCastException if the .NET member raises it
     * @throws system.OutOfMemoryException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.SetModified" target="_top">.NET documentation</a>
     */
    public void SetModified() throws Throwable, system.ArgumentException, system.InvalidOperationException, system.PlatformNotSupportedException, system.IndexOutOfRangeException, system.ArgumentOutOfRangeException, system.FormatException, system.RankException, system.NotSupportedException, system.ArrayTypeMismatchException, system.InvalidCastException, system.OutOfMemoryException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Invoke("SetModified");
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member SetParentRow.
     *
     * @param parentRow the argument of type {@code DataRow}
     * @param relation the argument of type {@code DataRelation}
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.SetParentRow" target="_top">.NET documentation</a>
     */
    public void SetParentRow(DataRow parentRow, DataRelation relation) throws Throwable, system.InvalidOperationException, system.PlatformNotSupportedException, system.ArgumentOutOfRangeException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Invoke("SetParentRow", parentRow == null ? null : parentRow.getJCOInstance(), relation == null ? null : relation.getJCOInstance());
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Invokes the .NET member SetParentRow.
     *
     * @param parentRow the argument of type {@code DataRow}
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.SetParentRow" target="_top">.NET documentation</a>
     */
    public void SetParentRow(DataRow parentRow) throws Throwable, system.ArgumentException, system.PlatformNotSupportedException, system.InvalidOperationException, system.FormatException, system.ArgumentOutOfRangeException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Invoke("SetParentRow", parentRow == null ? null : parentRow.getJCOInstance());
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }


    
    // Properties section
    
    /**
     * Gets the value of the .NET property HasErrors.
     *
     * @return the value of the property
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.HasErrors" target="_top">.NET documentation</a>
     */
    public boolean getHasErrors() throws Throwable {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectHasErrors = null;
        try {
            retObjectHasErrors = classInstance.Get("HasErrors");
            return (boolean)retObjectHasErrors;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into boolean", retObjectHasErrors != null ? retObjectHasErrors.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Gets the value of the .NET property RowState.
     *
     * @return the value of the property
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.RowState" target="_top">.NET documentation</a>
     */
    public DataRowState getRowState() throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ObjectDisposedException, system.InvalidOperationException, system.IndexOutOfRangeException, system.ArgumentOutOfRangeException, system.FormatException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectRowState = null;
        try {
            retObjectRowState = classInstance.Get("RowState");
            JCObject val = (JCObject)retObjectRowState;
            return new DataRowState(val);
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectRowState != null ? retObjectRowState.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Gets the value of the .NET property Table.
     *
     * @return the value of the property
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.Table" target="_top">.NET documentation</a>
     */
    public DataTable getTable() throws Throwable {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectTable = null;
        try {
            retObjectTable = classInstance.Get("Table");
            JCObject val = (JCObject)retObjectTable;
            return new DataTable(val);
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectTable != null ? retObjectTable.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Gets the value of the .NET property ItemArray.
     *
     * @return the value of the property
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.globalization.CultureNotFoundException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.ArrayTypeMismatchException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.ItemArray" target="_top">.NET documentation</a>
     */
    public final NetObject[] getItemArray() throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.ArgumentOutOfRangeException, system.globalization.CultureNotFoundException, system.IndexOutOfRangeException, system.FormatException, system.ArrayTypeMismatchException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectItemArray = null;
        try {
            ArrayList<NetObject> resultingArrayList = new ArrayList<NetObject>();
            retObjectItemArray = classInstance.Get("ItemArray");
            JCObject resultingObjects = (JCObject)retObjectItemArray;
            for (java.lang.Object resultingObject : resultingObjects) {
			    resultingArrayList.add(new NetObject(resultingObject));
            }
            NetObject[] resultingArray = new NetObject[resultingArrayList.size()];
            resultingArray = resultingArrayList.toArray(resultingArray);
            return resultingArray;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectItemArray != null ? retObjectItemArray.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Sets the value of the .NET property ItemArray.
     *
     * @param ItemArray the new value of the property
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.globalization.CultureNotFoundException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.RankException if the .NET member raises it
     * @throws system.IndexOutOfRangeException if the .NET member raises it
     * @throws system.ArrayTypeMismatchException if the .NET member raises it
     * @throws system.InvalidCastException if the .NET member raises it
     * @throws system.OutOfMemoryException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.ItemArray" target="_top">.NET documentation</a>
     */
    public void setItemArray(NetObject[] ItemArray) throws Throwable, system.ArgumentNullException, system.ArgumentException, system.PlatformNotSupportedException, system.NotSupportedException, system.ArgumentOutOfRangeException, system.globalization.CultureNotFoundException, system.InvalidOperationException, system.ObjectDisposedException, system.RankException, system.IndexOutOfRangeException, system.ArrayTypeMismatchException, system.InvalidCastException, system.OutOfMemoryException, system.threading.LockRecursionException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Set("ItemArray", toObjectFromArray(ItemArray));
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Gets the value of the .NET property RowError.
     *
     * @return the value of the property
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.RowError" target="_top">.NET documentation</a>
     */
    public java.lang.String getRowError() throws Throwable {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectRowError = null;
        try {
            retObjectRowError = classInstance.Get("RowError");
            return (java.lang.String)retObjectRowError;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into java.lang.String", retObjectRowError != null ? retObjectRowError.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Sets the value of the .NET property RowError.
     *
     * @param RowError the new value of the property
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.PlatformNotSupportedException if the .NET member raises it
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @throws system.FormatException if the .NET member raises it
     * @throws system.OutOfMemoryException if the .NET member raises it
     * @throws system.diagnostics.tracing.EventSourceException if the .NET member raises it
     * @throws system.collections.generic.KeyNotFoundException if the .NET member raises it
     * @throws system.threading.LockRecursionException if the .NET member raises it
     * @throws system.RankException if the .NET member raises it
     * @throws system.ArrayTypeMismatchException if the .NET member raises it
     * @throws system.threading.SynchronizationLockException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Data.DataRow.RowError" target="_top">.NET documentation</a>
     */
    public void setRowError(java.lang.String RowError) throws Throwable, system.PlatformNotSupportedException, system.ArgumentNullException, system.ArgumentException, system.ArgumentOutOfRangeException, system.InvalidOperationException, system.NotSupportedException, system.FormatException, system.OutOfMemoryException, system.diagnostics.tracing.EventSourceException, system.collections.generic.KeyNotFoundException, system.threading.LockRecursionException, system.RankException, system.ArrayTypeMismatchException, system.threading.SynchronizationLockException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        try {
            classInstance.Set("RowError", RowError);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }



    // Instance Events section
    

}