/*
 *  MIT License
 *
 *  Copyright (c) 2020-2026 MASES s.r.l.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

/**************************************************************************************
 * <auto-generated>
 *      This code was generated from a template using JCOReflector v. 2.0.0.0
 * 
 *      Manual changes to this file may cause unexpected behavior in your application.
 *      Manual changes to this file will be overwritten if the code is regenerated.
 * </auto-generated>
 *************************************************************************************/

package system.web.ui.webcontrols;

import org.mases.jcobridge.*;
import org.mases.jcobridge.netreflection.*;
import java.util.ArrayList;

// Import section
import system.collections.specialized.IOrderedDictionary;
import system.collections.specialized.IOrderedDictionaryImplementation;
import system.web.ui.webcontrols.DataKey;


/**
 * The base .NET class managing System.Web.UI.WebControls.DataKey, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
 * <p>
 * 
 * .NET documentation at <a href="https://learn.microsoft.com/dotnet/api/System.Web.UI.WebControls.DataKey" target="_top">https://learn.microsoft.com/dotnet/api/System.Web.UI.WebControls.DataKey</a>
 * <p>
 *
 * Powered by JCOBridge: more info at <a href="https://www.jcobridge.com" target="_top">https://www.jcobridge.com</a>
 *
 * @author  MASES s.r.l https://masesgroup.com
 * @version 2.0.0.0
 */
public class DataKey extends NetObject  {
    /**
     * Fully assembly qualified name: System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
     */
    public static final String assemblyFullName = "System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a";
    /**
     * Assembly name: System.Web
     */
    public static final String assemblyShortName = "System.Web";
    /**
     * Qualified class name: System.Web.UI.WebControls.DataKey
     */
    public static final String className = "System.Web.UI.WebControls.DataKey";
    static JCOBridge bridge = JCOBridgeInstance.getInstance(assemblyFullName);
    /**
     * The type managed from JCOBridge. See {@link JCType}
     */
    public static JCType classType = createType();
    static JCEnum enumInstance = null;
    JCObject classInstance = null;

    static JCType createType() {
        try {
            String classToCreate = className + ", "
                    + (JCOReflector.getUseFullAssemblyName() ? assemblyFullName : assemblyShortName);
            if (JCOReflector.getDebug())
                JCOReflector.writeLog("Creating %s", classToCreate);
            JCType typeCreated = bridge.GetType(classToCreate);
            if (JCOReflector.getDebug())
                JCOReflector.writeLog("Created: %s",
                        (typeCreated != null) ? typeCreated.toString() : "Returned null value");
            return typeCreated;
        } catch (JCException e) {
            JCOReflector.writeLog(e);
            return null;
        }
    }

    void addReference(String ref) throws Throwable {
        try {
            bridge.AddReference(ref);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }
    /**
     * Internal constructor. Use with caution
     *
     * @param instance the underlying bridge object: it must be a {@code JCObject}
     * @throws Throwable if {@code instance} is not a {@code JCObject}
     */
    public DataKey(java.lang.Object instance) throws Throwable {
        super(instance);
        if (instance instanceof JCObject) {
            classInstance = (JCObject) instance;
        } else
            throw new Exception("Cannot manage object, it is not a JCObject");
    }

    public String getJCOAssemblyName() {
        return assemblyFullName;
    }

    public String getJCOClassName() {
        return className;
    }

    public String getJCOObjectName() {
        return className + ", " + (JCOReflector.getUseFullAssemblyName() ? assemblyFullName : assemblyShortName);
    }

    public java.lang.Object getJCOInstance() {
        return classInstance;
    }

    public void setJCOInstance(JCObject instance) {
        classInstance = instance;
        super.setJCOInstance(classInstance);
    }

    public JCType getJCOType() {
        return classType;
    }
    /**
     * Try to cast the {@link IJCOBridgeReflected} instance into {@link DataKey}, a cast assert is made to check if types are compatible.
     * @param from {@link IJCOBridgeReflected} instance to be casted
     * @return {@link DataKey} instance
     * @throws java.lang.Throwable in case of error during cast operation
     */
    public static DataKey cast(IJCOBridgeReflected from) throws Throwable {
        NetType.AssertCast(classType, from);
        return new DataKey(from.getJCOInstance());
    }

    // Constructors section
    
    public DataKey() throws Throwable {
    }

    /**
     * Initializes a new instance by invoking the .NET constructor.
     *
     * @param keyTable the argument of type {@code IOrderedDictionary}
     * @throws Throwable if the .NET constructor fails
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Web.UI.WebControls.DataKey.-ctor" target="_top">.NET documentation</a>
     */
    public DataKey(IOrderedDictionary keyTable) throws Throwable {
        try {
            // add reference to assemblyName.dll file
            addReference(JCOReflector.getUseFullAssemblyName() ? assemblyFullName : assemblyShortName);
            setJCOInstance((JCObject)classType.NewObject(keyTable == null ? null : keyTable.getJCOInstance()));
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Initializes a new instance by invoking the .NET constructor.
     *
     * @param keyTable the argument of type {@code IOrderedDictionary}
     * @param keyNames the argument of type {@code java.lang.String[]}
     * @throws Throwable if the .NET constructor fails
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Web.UI.WebControls.DataKey.-ctor" target="_top">.NET documentation</a>
     */
    public DataKey(IOrderedDictionary keyTable, java.lang.String[] keyNames) throws Throwable {
        try {
            // add reference to assemblyName.dll file
            addReference(JCOReflector.getUseFullAssemblyName() ? assemblyFullName : assemblyShortName);
            setJCOInstance((JCObject)classType.NewObject(keyTable == null ? null : keyTable.getJCOInstance(), keyNames));
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }



    
    // Methods section
    
    /**
     * Invokes the .NET member Equals.
     *
     * @param other the argument of type {@code DataKey}
     * @return the value returned by the .NET member
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.MissingMethodException if the .NET member raises it
     * @throws system.reflection.TargetInvocationException if the .NET member raises it
     * @throws system.globalization.CultureNotFoundException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Web.UI.WebControls.DataKey.Equals" target="_top">.NET documentation</a>
     */
    public boolean Equals(DataKey other) throws Throwable, system.ArgumentException, system.ArgumentNullException, system.InvalidOperationException, system.MissingMethodException, system.reflection.TargetInvocationException, system.globalization.CultureNotFoundException, system.NotSupportedException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectEquals = null;
        try {
            retObjectEquals = classInstance.Invoke("Equals", other == null ? null : other.getJCOInstance());
            return (boolean)retObjectEquals;
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to convert %s into boolean", retObjectEquals != null ? retObjectEquals.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * @deprecated Not for public use because the method is implemented in .NET with an explicit interface.
     *    Use the static ToIStateManager method available in IStateManager to obtain an object with an invocable method
     *
     * @return the value returned by the .NET member
     * @throws Throwable always, with an {@code UnsupportedOperationException}
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Web.UI.IStateManager.SaveViewState" target="_top">.NET documentation</a>
     */
    @Deprecated
    public NetObject SaveViewState() throws Throwable {
        throw new java.lang.UnsupportedOperationException("Not for public use because the method is implemented with an explicit interface. Use ToIStateManager to obtain the full interface.");
    }

    /**
     * @deprecated Not for public use because the method is implemented in .NET with an explicit interface.
     *    Use the static ToIStateManager method available in IStateManager to obtain an object with an invocable method
     *
     * @param state the argument of type {@code NetObject}
     * @throws Throwable always, with an {@code UnsupportedOperationException}
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Web.UI.IStateManager.LoadViewState" target="_top">.NET documentation</a>
     */
    @Deprecated
    public void LoadViewState(NetObject state) throws Throwable {
        throw new java.lang.UnsupportedOperationException("Not for public use because the method is implemented with an explicit interface. Use ToIStateManager to obtain the full interface.");
    }

    /**
     * @deprecated Not for public use because the method is implemented in .NET with an explicit interface.
     *    Use the static ToIStateManager method available in IStateManager to obtain an object with an invocable method
     *
     * @throws Throwable always, with an {@code UnsupportedOperationException}
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Web.UI.IStateManager.TrackViewState" target="_top">.NET documentation</a>
     */
    @Deprecated
    public void TrackViewState() throws Throwable {
        throw new java.lang.UnsupportedOperationException("Not for public use because the method is implemented with an explicit interface. Use ToIStateManager to obtain the full interface.");
    }


    
    // Properties section
    
    /**
     * Gets the value of the .NET property Values.
     *
     * @return the value of the property
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @throws system.ArgumentNullException if the .NET member raises it
     * @throws system.ArgumentException if the .NET member raises it
     * @throws system.InvalidOperationException if the .NET member raises it
     * @throws system.MissingMethodException if the .NET member raises it
     * @throws system.reflection.TargetInvocationException if the .NET member raises it
     * @throws system.NotImplementedException if the .NET member raises it
     * @throws system.ArgumentOutOfRangeException if the .NET member raises it
     * @throws system.globalization.CultureNotFoundException if the .NET member raises it
     * @throws system.resources.MissingManifestResourceException if the .NET member raises it
     * @throws system.ObjectDisposedException if the .NET member raises it
     * @throws system.NotSupportedException if the .NET member raises it
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Web.UI.WebControls.DataKey.Values" target="_top">.NET documentation</a>
     */
    public IOrderedDictionary getValues() throws Throwable, system.ArgumentNullException, system.ArgumentException, system.InvalidOperationException, system.MissingMethodException, system.reflection.TargetInvocationException, system.NotImplementedException, system.ArgumentOutOfRangeException, system.globalization.CultureNotFoundException, system.resources.MissingManifestResourceException, system.ObjectDisposedException, system.NotSupportedException {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectValues = null;
        try {
            retObjectValues = classInstance.Get("Values");
            JCObject val = (JCObject)retObjectValues;
            return new IOrderedDictionaryImplementation(val);
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectValues != null ? retObjectValues.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }

    /**
     * Gets the value of the .NET property Value.
     *
     * @return the value of the property
     * @throws Throwable if the call fails in the bridge or in the CLR
     * @see <a href="https://learn.microsoft.com/dotnet/api/System.Web.UI.WebControls.DataKey.Value" target="_top">.NET documentation</a>
     */
    public NetObject getValue() throws Throwable {
        if (classInstance == null)
            throw new java.lang.UnsupportedOperationException("classInstance is null.");
        java.lang.Object retObjectValue = null;
        try {
            retObjectValue = classInstance.Get("Value");
            JCObject val = (JCObject)retObjectValue;
            return new NetObject(val);
        } catch (java.lang.ClassCastException cce) {
            throw new java.lang.IllegalStateException(java.lang.String.format("Failed to cast %s into JCObject", retObjectValue != null ? retObjectValue.getClass() : "null"), cce);
        } catch (JCNativeException jcne) {
            throw translateException(jcne);
        }
    }



    // Instance Events section
    

}