<?xml version="1.0" encoding="utf-8"?>
<JavaBuilderEventArgs xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <LogLevel>Info</LogLevel>
  <SourceFolder>netreflected</SourceFolder>
  <SplitFolderByAssembly>true</SplitFolderByAssembly>
  <JDKFolder>jdk</JDKFolder>
  <JDKTarget>Version8</JDKTarget>
  <JDKToolExtraOptions></JDKToolExtraOptions>
</JavaBuilderEventArgs>