# This is a basic workflow to help you get started with Actions

name: Reflect, test and commit

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    # only trigger on branches, not on tags
    branches: '**'
    paths-ignore:
      - 'docs/**'
   
  workflow_dispatch:
    inputs:
      ExecuteOnMoreOSes:
        description: 'Executes tests on more Oses'
        required: false
        default: false
        type: boolean
      ExecuteOnLargerJDKVendorSet:
        description: 'Executes tests on more JDK vendor'
        required: false
        default: false
        type: boolean
      ExecuteOnLargerJDKVersionSet:
        description: 'Executes tests on more JDK version'
        required: false
        default: false
        type: boolean
      EnableLinuxTests:
        description: 'Enable tests in Linux'
        required: false
        default: false
        type: boolean
      EnableWindowsTests:
        description: 'Enable tests in Windows'
        required: false
        default: false
        type: boolean
      EnableMacOSTests:
        description: 'Enable tests in MacOS'
        required: false
        default: false
        type: boolean
      ForceExecution:
        description: 'Force execution of workflow'
        required: false
        default: false
        type: boolean
      GeneratePR:
        description: 'Generate the PR at the end'
        required: false
        default: false
        type: boolean

  schedule:
    - cron: "0 4 * * 6"

# This workflow contains two jobs called "check" and "build_windows"
jobs:
  # Verify if a build is needed
  check:
    if: ${{ github.repository_owner == 'masesgroup' || (github.repository_owner != 'masesgroup' && github.ref_name != 'master') }} #do not execute on master outside main repo
    name: Check changed files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job || steps.force_execute.outputs.run_job }}
    runs-on: ubuntu-22.04
    steps:
      - name: Force check on true
        id: force_execute
        if: ${{ github.event_name != 'push' }}
        run: echo "run_job=true" >> $GITHUB_OUTPUT
        
      - name: Create modified file list
        if: ${{ github.event_name == 'push' }}
        id: get_changed_files
        uses: masesgroup/retrieve-changed-files@v4
        with:
          format: 'csv'

      - name: Check modified file list
        if: ${{ github.event_name == 'push' }}
        id: check_files
        run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.get_changed_files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
              if [[ $added_modified_file == ".github/workflows/reflect_test_commit.yaml"* ]]; then
                echo "$added_modified_file is under the directory '.github/workflows'."
                echo "run_job=true" >> $GITHUB_OUTPUT
                break
              fi
              if [[ $added_modified_file == ".github/workflows/reflect_test_commit_common.yaml"* ]]; then
                echo "$added_modified_file is under the directory '.github/workflows'."
                echo "run_job=true" >> $GITHUB_OUTPUT
                break
              fi
              if [[ $added_modified_file == "src/jvm/src/JCOReflector/"* ]]; then
                echo "$added_modified_file is under the directory 'src/jvm/src/JCOReflector'."
                echo "run_job=true" >> $GITHUB_OUTPUT
                break
              fi
              if [[ $added_modified_file == "src/net/"* ]]; then
                echo "$added_modified_file is under the directory 'src/'."
                echo "run_job=true" >> $GITHUB_OUTPUT
                break
              fi
              if [[ $added_modified_file == "tests/jvm/"* ]]; then
                echo "$added_modified_file is under the directory 'tests/jvm/'."
                echo "run_job=true" >> $GITHUB_OUTPUT
                break
              fi
          done

  build:
    needs: check
    if: "always() && needs.check.outputs.run_job == 'true'"
    permissions:
      contents: read
      pull-requests: write
      attestations: write
      packages: write
      id-token: write
      artifact-metadata: write
    uses: ./.github/workflows/reflect_test_commit_common.yaml
    with:
      ExecuteOnMoreOSes: ${{ inputs.ExecuteOnMoreOSes || github.event_name == 'schedule' }}
      ExecuteOnLargerJDKVendorSet: ${{ inputs.ExecuteOnLargerJDKVendorSet || github.ref_name == 'master' || github.event_name == 'schedule' }}
      ExecuteOnLargerJDKVersionSet: ${{ inputs.ExecuteOnLargerJDKVersionSet || github.ref_name == 'master' || github.event_name == 'schedule' }}
      EnableLinuxTests: true
      EnableWindowsTests: ${{ inputs.EnableWindowsTests || github.ref_name == 'master' || github.event_name == 'schedule' }}
      EnableMacOSTests: ${{ inputs.EnableMacOSTests || github.event_name == 'schedule' }}
      ForceExecution: ${{ inputs.ForceExecution || false }}
      GeneratePR: ${{ inputs.GeneratePR || false }}
    secrets:
      actor: ${{ github.actor }}
      GITHUB_TOKEN_INHERITED: ${{ secrets.GITHUB_TOKEN }}
      JCOBRIDGE_ENCODED: ${{ secrets.JCOBRIDGE_ENCODED_2_6_8 }}